services:
  database:
    image: postgres
    restart: always
    container_name: todos-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data