import clsx from 'clsx';
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { AuthProvider } from '@/features/auth/components/AuthProvider';
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={clsx('antialiased', outfit.className)}
        >
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
